# b = set(map(str,input().split(" ")))
# c= list(map(str,input().split(" ")))
# d= list(map(str,input().split(" ")))
# d.pop(0)
# set2=set(d)
# c.pop(0)
# set1=set(c)
# print(set1)
# print(set2)
# set1.update(set2)
# print(set1)
a={"a","b","c","d","e","f","g","h"}
print(len(a))